#!/usr/bin/env bash
input_path="$1"
output_path="~/Documents/map_naarPNG"
bestand_ext=".jpg"
for image in "$input_path"/*"$bestand_ext"; do
	echo "$image"
  if [[ -f "$image" ]]; then
    
    png_ext=".png"
    convert "$image" -resize 128x128 "${image%.*}${png_ext}" 
    echo "$image" 
  fi
done
