#!/usr/bin/env bash
path="$1"
echo "this is the image path: $path"

if [[ ! -d "$Afbeeldingen" ]]; then
  mkdir Afbeeldingen   
fi
for image in "$path"/*; do
  if [[ -f "$image" ]]; then
    mv "$image" Afbeeldingen
  fi
done
